spring:
  datasource:
    url: jdbc:mysql://localhost:3306/companymanager
    username: commanager
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
